### PR TITLE
Rename Formik directory to formik

### LINKED ISSUE #12: Fix webpack config
https://github.com/bigbinary/nitroui/blob/9cc7a0b365f8618fe34672cedbc938c46500ad05/webpack.config.js#L7

I think a minor spelling mistake occurred. It should be `Formik` with a capital `F` in the path.

@yedhink _a

### PR DESCRIPTION
**Pull request by yedhink**
Fixes #12 

Can you review and merge the PR?
@edwinbbu _a

### CODE REVIEW

**Comment by vinay0x** [comment]
@yedhink _a Please make the folder name lowercase to be inline with the import path. That's better.

**Comment by yedhink** [comment]
@vinay0x _a

Have made the requested changes.

**Comment by vinay0x** [comment]
@yedhink _a Can you try running `yarn build` and see if anything is throwing error? Also, please do a case sensitive search for instances of Formik and change it to formik.

**Comment by yedhink** [comment]
@vinay0x _a

No errors were thrown in the build process. 

No standalone `Formik` references exists. Only cameCased and PascalCased ones exist:-
image

**Pull request merged**
